### PR TITLE
Fix Fiji update site check

### PR DESCRIPTION
**Pull request by imagejan**
After @ctrueden 's recent change on the [List of update sites](http://fiji.sc/index.php?title=List_of_update_sites&diff=next&oldid=15648), the updater was throwing the exception below. This change should fix it.

    java.io.IOException: Invalid page: List of update sites
	at net.imagej.updater.util.AvailableSites.getAvailableSites(AvailableSites.java:112)
	at net.imagej.updater.util.AvailableSites.initializeSites(AvailableSites.java:138)
	at net.imagej.updater.util.AvailableSites.initializeAndAddSites(AvailableSites.java:187)
	at net.imagej.ui.swing.updater.ImageJUpdater.run(ImageJUpdater.java:107)
	at org.scijava.command.CommandModule.run(CommandModule.java:201)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:167)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:126)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:65)
	at org.scijava.thread.DefaultThreadService$2.call(DefaultThreadService.java:191)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
    java.io.IOException: Invalid page: List of update sites
	at net.imagej.updater.util.AvailableSites.getAvailableSites(AvailableSites.java:112)
	at net.imagej.updater.util.AvailableSites.initializeSites(AvailableSites.java:138)
	at net.imagej.updater.util.AvailableSites.initializeAndAddSites(AvailableSites.java:187)
	at net.imagej.ui.swing.updater.ImageJUpdater.run(ImageJUpdater.java:107)
	at org.scijava.command.CommandModule.run(CommandModule.java:201)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:167)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:126)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:65)
	at org.scijava.thread.DefaultThreadService$2.call(DefaultThreadService.java:191)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

### CODE REVIEW

**Comment by hinerm** [comment]
You are awesome @imagejan

**Comment by hinerm** [comment]
I immediately cut a release of this and pushed it to the ImageJ update site. Because of the complexity of the updater I am not actually 100% sure that was the right thing to do. It appears to have worked but if anything catastrophic happens please yell at @ctrueden and me.

**Comment by ctrueden** [comment]
Grah! I had this change (and more) already committed locally, but never pushed because I had to run off early today.

**Comment by ctrueden** [comment]
I rebased and pushed the remnants of my commit as 4bdc60f8183960baf842d8d1e664c7e947724afd.

**Comment by ctrueden** [comment]
> It appears to have worked but if anything catastrophic happens please yell at @ctrueden and me.

Yeah, it fixes the exception, although old installations will still see the exception stack trace once before the update. Oh well...

**Comment by imagejan** [comment]
Thanks.
I noticed that the URL field still shows "http://fiji.sc/update/" for the Fiji update site in the *Manage update sites* dialog after updating a Fiji installation. The URL might be saved in the local *db.xml.gz* ?

**Comment by dscho** [comment]
> the URL field still shows "http://fiji.sc/update/" for the Fiji update site

This would have required a change similar to the change when Fiji migrated away from the MPI-CBG  (because that institute already had stopped supporting the Fiji maintainer, so I had to fear that they would stop supporting the Fiji server, too, which was eventually not the case, but by then we had migrated to LOCI's servers already): fiji/fiji@b4459544c000f4d51d1ec23f279d9cdb19c1d32b

**Comment by ctrueden** [comment]
Thanks @dscho—done in 5cb22ded192ff155fc9084b12bf6203fa60592c5.

**Pull request merged**
